src/convert/sigma.rs
Loading empty yaml files into chainsaw would cause it to panic due to a
stupid assumption. This has now been taken care of.
=> fix: handle empty files #3

src/check.rs, src/convert/sigma.rs, src/hunt/mod.rs, src/hunt/modules.rs
We parsed these very incorrectly, this PR should rectify that (#37). In addition as this is now fixed I have re-reverted the string casting issue to fix #19.
~~This change has increased the number of detections with the default data set, so this will need double checking.~~
Done a diff and the only difference is the addition of some rules that were failing due to the EventID string issue. So I think this is good to go.
=> Correctly convert Sigma's Rule Collection rules

src/convert/sigma.rs, src/hunt/mod.rs, src/main.rs, src/search.rs, src/write.rs
Adds the changes required so that `--output` can be used in chainsaw as it seems some times pipe redirection is not viable. This probably needs a bit of testing but as always we lack the time and people (well that is my excuse anyways) :)
=> feat: add in output command as requested for #60

README.md
Thanks for the nice tool :)
The directory names of Sigma Rules and EVTX-Attack-Samples in README(Quick Start Guide) were actually a little different, so I fixed them.
=> Update README: Change the folder(evtx,sigma) name specified in the command

rules/antivirus/sophos.yml
Thanks for fixing issue #132! I tested it there and everything works as expected. With this PR I added SHA1 Support based on the Events I have seen from Sophos System Protection and added it as a Provider
=> Add SHA1 Support to Sophos Rule and Add System Provider

rules/antivirus/symantec.yml
The Symantec logs entries do not seem easy to parse with a lot of \r\ns separating the log entries. They are still readable however so I added the entire event details to the Threat Name field 
The log entries with the rule are filtered by EventID to reduce noise as on a real system there are a lot of events that repeat such as antivirus definitions updated.
I will be attaching a sample Antivirus.csv and an EventLog with some events taken from a Virtual Machine to make for an easier review
[SymantecEventLog.zip](https://github.com/WithSecureLabs/chainsaw/files/11642662/SymantecEventLog.zip)
=> Create Antivirus Rule for Symantec Endpoint Protection

rules/microsoft_rasvpn_events/eid_20220_20227_rasvpn_client_connection_error.yml, rules/microsoft_rasvpn_events/eid_20221_to_20225_rasvpn_client_connection_establishment.yml, rules/microsoft_rasvpn_events/eid_20226_rasvpn_client_connection_termination.yml, rules/microsoft_rasvpn_events/eid_20250_20274_rasvpn_server_logon.yml, rules/microsoft_rasvpn_events/eid_20253_20255_connection_error.yml, rules/microsoft_rasvpn_events/eid_20271_rasvpn_server_authentication_error.yml, rules/microsoft_rasvpn_events/eid_20272_20275_rasvpn_server_logoff.yml
This PR adds 7 rules to detect connection activity on Microsoft Remote Access VPN on both client and server sides.
Reference: https://github.com/synacktiv/forensic-msvpn
=> Add rules for Microsoft Remote Access VPN (client and server)

src/analyse/srum.rs
SRUM database entries can have an unknown AppId (no entry in SruDbIdMapTable). Instead of throwing an error, the SRUM parser will use the None value for unknown AppId and UserId values.
=> fix: handle unknown AppId and UserId values (no entry in SruDbIdMapTable)

rules/antivirus/windows_defender.yml
This updates the windows_defender.yml rule file to filter for EventIDs instead of saving all of the EventIDs to the spreadsheet. This should cut down on the noise of the resulting antivirus file. Tested on several engagements and works well.
=> Update Windows Defender rule to filter for key EventIDs

rules/microsoft_rasvpn_events/eid_20220_20227_rasvpn_client_connection_error.yml, rules/microsoft_rasvpn_events/eid_20221_to_20225_rasvpn_client_connection_establishment.yml
I noticed these typos when I was looking through the rules for inspiration. It should make sense as to why they were corrected.
=> Fixes to rasvpn rules

rules/service_installation/credential_dumping_tools.yml, rules/service_installation/csexec.yml, rules/service_installation/krbrelayup.yml, rules/service_installation/meterpreter_cobalt_strike_getsystem.yml, rules/service_installation/powershell.yml, rules/service_installation/processhacker.yml, rules/service_installation/remote_access_tools.yml, rules/service_installation/smbexec.yml, rules/service_installation/suspicious_commands.yml, rules/service_installation/suspicious_paths.yml, rules/service_installation/sysinternals_psexec.yml, rules/service_installation/tap0901.yml
These are based on the sigma rules [here](https://github.com/SigmaHQ/sigma/tree/master/rules/windows/builtin/system/service_control_manager) with several adjustments made based on research specifically for these rules. 
Attached is a series of log files I used during my testing [EVTX_7045.zip](https://github.com/WithSecureLabs/chainsaw/files/13801226/EVTX_7045.zip). These were custom made in a virtual machine due to lack of samples available (Especially for Remote Access Tools) in addition to using the evtx samples from [Hayabusa-sample-evtx](https://github.com/Yamato-Security/Hayabusa-sample-evtx). Most of the rules are accounted for in these samples however some I relied on the docs for the tools to generate the rules. 
Thanks again for your assistance in #149 as without this I would …
=> Service Installation 7045 Rules

mappings/sigma-event-logs-all.yml
This is a continuation of Pull Request #130 and reduces the false positive rate of sigma rules. Using [these](https://github.com/Yamato-Security/hayabusa-sample-evtx) event logs as a test I managed to reduce the sigma.csv from 5083KB to 4781KB a decrease of around 5.94%. 
Unfortunately I could not figure out how to use multiple EventID filters for some of these so there is most likely still some improvement that could be made here.
I tried both of these with the top one not erroring but continuing to show 4688 events for process_creation instead of taking them off due to me wanting to just have EventIDs 1 and 999 for testing. The second one errored claiming it was duplicated. 
This does not necessarily hold this pull request up as I can always create a new one after this is merged if you …
=> Update Sigma Mapping File to Reduce False Positives

rules/antivirus/kaspersky.yml, rules/antivirus/mcafee.yml, rules/antivirus/windows_security_essentials.yml
Attached are rules for McAfee and Trellix Endpoint Security, Kaspersky Endpoint Security and Windows Security Essentials (It actually still gets Definition Updates shockingly!). 
Events for testing are attached [AV Test.zip](https://github.com/WithSecureLabs/chainsaw/files/13833610/AV.Test.zip)
=> McAfee, Trellix, Kaspersky and Microsoft Windows Security Essentials Rules

src/main.rs, src/search.rs
Change the default behaviour when multiple tau rules are provided from logical AND to logical OR.
Extend the 'match_all' flag to toggle multiple tau rules from AND to OR conditions
=> feat: extend match_all option to tau patterns

src/file/evtx.rs, src/file/json.rs, src/main.rs, src/search.rs
Flipping default behaviour to match_all, with a flag to match_any instead.
=> fix: change default search behaviour to match_all

src/main.rs
- Enable the dump command to process multiple files at the same time
- Recursively load files from directories
- Filter file types with option `--extension`
=> feat(dump): allow dumping of multiple files

rules/powershell/eid_400_powershell_engine_state_available.yml, rules/powershell/eid_403_powershell_engine_state_stopped.yml
As per #177 here are rules for PowerShell 400 and 403 Events. This can highlight PowerShell Scripts that aren't captured by other PowerShell events. This was confirmed when I was on a case and this is only place the PowerShell commands were recorded.
=> Add PowerShell Rules

rules/service_tampering/mssql_sus_behavior.yml, rules/service_tampering/xp_cmdshell_enabled.yml
This PR contains rules for the event ID '15457' for MSSQL. These rules have been highly successful in internal investigations where threat actors have exhibited this behavior. I hope anyone else utilizing chainsaw gets great value out of these rules! 
Screenshot below shows true positives of the rules firing:
Please let me know if I need to change anything with this PR. Thanks!
=> feature: MSSQL suspicious behavior rules

src/file/esedb/srum.rs
This PR is related to the 'chainsaw analyse srum' feature. It will prevent decoding errors when parsing the SruDbIdMapTable table, for example with Chinese characters.
=> fix: prevent decoding errors when parsing the SruDbIdMapTable table

rules/mft/adamntds_dit_mft.yml, rules/mft/pstools_mft.yml, rules/mft/shadow_dumper_mft.yml
Some more MFT rules. I attempted to further reduce the false positive entries for NTDS.DIT. 
ADAMNTDS.DIT can be abused too so created a separate rule for that based on [here](https://www.synacktiv.com/en/publications/using-ntdissector-to-extract-secrets-from-adam-ntds-files). 
Also added Shadow Dumper support from [here](https://github.com/Offensive-Panda/ShadowDumper). 
Also added the rest of the PSTools folder as this frequently pops up
=> More MFT Rules - Fix NTDS.DIT matching ADAMNTDS.DIT and Add Shadow Dumper and PSTools

README.md
the following updates README to include install and build instructions utilizing Nix and `flake.nix` associated with this repo 
it's up for further discussion if this section can be kept as seperate section, or whether needs a little re-write and add it to currently existing `Downloading and Running` section of README
=> update README - add install/build with Nix instructions

rules/mft/advanced_ip_scanner_mft.yml, rules/mft/advanced_port_scanner_mft.yml, rules/mft/netscan_mft.yml
Turns out Advanced Port Scanner and Advanced IP Scanner share a lot of the same code when running the latest versions in a VM. This allowed me to spot common themes between the two including something I missed on the original MFT rule to help identify presence. I could have included .qm and .tpl files but these were a bit noisy and unlikely to make much difference keeping them in. 
Additionally added the .rnd WinSCP random seed file to the WinSCP rule and added a Netscan rule to cover this tool which is another commonly abused tool on cases.
=> Add Netscan and Advanced Port Scanner and Modify WinSCP and Advanced IP Scanner MFT Rules

rules/evtx/service_tampering/remote_registry_usage.yml
Hello! 
This rule has successfully detected Impacket-Secretsdump, CrackMapExec, and NetExec for remote registry dumping. I am keeping it as a medium because I am unsure how to bin the time between the service states to ensure a higher detection fidelity. Feel free to let me know if you need any changes!
Thanks!
=> Feat: Rule - Remote Registry Usage

src/main.rs
- Implement rayon processing for search 
**Searching**
Before: 
```
➜  release git:(master) time ./chainsaw search foo ~/Downloads/evtx --skip-errors -o foo
██████╗██╗  ██╗ █████╗ ██╗███╗   ██╗███████╗ █████╗ ██╗    ██╗
██╔════╝██║  ██║██╔══██╗██║████╗  ██║██╔════╝██╔══██╗██║    ██║
██║     ███████║███████║██║██╔██╗ ██║███████╗███████║██║ █╗ ██║
██║     ██╔══██║██╔══██║██║██║╚██╗██║╚════██║██╔══██║██║███╗██║
╚██████╗██║  ██║██║  ██║██║██║ ╚████║███████║██║  ██║╚███╔███╔╝
╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝
By WithSecure Countercept (@FranticTyping, @AlexKornitzer)
[+] Loading forensic artefacts from: /Users/jamesdorgan/Downloads/evtx
[+] Loaded 2240 forensic files (9.4 GB)
[+] Searching forensic artefacts...
[+] Found 616 hits
./chainsaw <snip>  212.15s user …
```
=> feat: implement rayon for search

Cargo.lock, Cargo.toml, src/file/mft.rs, src/file/mod.rs, src/hunt.rs, src/main.rs, src/search.rs
Our current MFT support doesn't look at data streams stored in MFT entries. These data streams are a goldmine of information for Incident Responders. 
This PR aims to introduce three key features:
1. Chainsaw is able to extract MFT data streams, decode them and include them in the YAML and JSON outputs.
2. Chainsaw is able to extract MFT data streams, decode them and write them to disk
3. Chainsaw is able to apply detection logic to data streams
This PR should address issues: #190 #191 
By default, Chainsaw will now extract data streams and include them in the default output. Stream names and values are shown, with values being in a hexstring format:
```
➜  release ./chainsaw dump ~/Artefacts/MFT/Win10/APTSimulatorVM/\$MFT
██████╗██╗  ██╗ █████╗ ██╗███╗   ██╗███████╗ █████╗ ██╗    ██╗ …
```
=> feat(dump) - extract, decode and write MFT streams

mappings/sigma-event-logs-all.yml
Mapping for sigma PreAuthType field, found in Keberos Authentication Service event ID 4768
Supports https://github.com/SigmaHQ/sigma/pull/5512
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
<Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
<EventID>4768</EventID> 
<Version>0</Version> 
<Level>0</Level> 
<Task>14339</Task> 
<Opcode>0</Opcode> 
<Keywords>0x8020000000000000</Keywords> 
<TimeCreated SystemTime="2024-05-28T06:32:40.2463627Z" /> 
<EventRecordID>6231</EventRecordID> 
<Correlation /> 
<Execution ProcessID="752" ThreadID="3188" /> 
<Channel>Security</Channel> 
<Computer>DC01.acme.corp</Computer> 
<Security /> 
</System>
<EventData>
<Data Name="TargetUserName">john.smith</Data> 
<Data …
```
=> Support for PreAuthType field
